// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBoa_6VI-WyqsT9Qr9bW4MirU73pOAeBQ',
    appId: '1:552872113249:web:960284b68ffecd558e6620',
    messagingSenderId: '552872113249',
    projectId: 'fir-app-e4198',
    authDomain: 'fir-app-e4198.firebaseapp.com',
    storageBucket: 'fir-app-e4198.firebasestorage.app',
    measurementId: 'G-5NDK8D1QC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmgr41NNRq3fzagWDAcAJLIoY9WjjUB44',
    appId: '1:552872113249:android:098e03fc4e664a598e6620',
    messagingSenderId: '552872113249',
    projectId: 'fir-app-e4198',
    storageBucket: 'fir-app-e4198.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdle8hq4dq9K-PhzBsWc4eN-KhEBegEdI',
    appId: '1:552872113249:ios:d562d9718deceee18e6620',
    messagingSenderId: '552872113249',
    projectId: 'fir-app-e4198',
    storageBucket: 'fir-app-e4198.firebasestorage.app',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdle8hq4dq9K-PhzBsWc4eN-KhEBegEdI',
    appId: '1:552872113249:ios:d562d9718deceee18e6620',
    messagingSenderId: '552872113249',
    projectId: 'fir-app-e4198',
    storageBucket: 'fir-app-e4198.firebasestorage.app',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBoa_6VI-WyqsT9Qr9bW4MirU73pOAeBQ',
    appId: '1:552872113249:web:3f61691620572b0f8e6620',
    messagingSenderId: '552872113249',
    projectId: 'fir-app-e4198',
    authDomain: 'fir-app-e4198.firebaseapp.com',
    storageBucket: 'fir-app-e4198.firebasestorage.app',
    measurementId: 'G-BRW873L676',
  );
}
